version: '3.9'

services:

  source-db:
    container_name: "postgres"
    image: "postgres:16"
    restart: "always"
    ports:
      - "5432:5432"
    shm_size: "128mb"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - './src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql'
    command: >
      postgres 
      -c wal_level=logical 
      -c max_wal_senders=10 
      -c max_replication_slots=10
    networks:
      - "debezium-net"

  adminer:
    container_name: "pgtool"
    image: "adminer:standalone"
    restart: "always"
    ports:
      - "8032:8080"
    depends_on:
      - "source-db"
    networks:
      - "debezium-net"

  sink-db:
    container_name: "postgres2"
    image: "postgres:16"
    restart: "always"
    ports:
      - "5433:5432"
    shm_size: "128mb"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    networks:
      - "debezium-net"

  app:
    container_name: "app"
    image: "everlastingeraser/simple-app:1.0.0"
    restart: "always"
    ports:
      - "8080:8080"
    depends_on:
      - "sink-db"
    networks:
      - "debezium-net"

  kafka:
    container_name: "kafka"
    image: "bitnami/kafka:3.7.1"
    restart: "always"
    ports:
      - "9092:9092"
    environment:
      - "KAFKA_CFG_NODE_ID=0"
      - "KAFKA_CFG_PROCESS_ROLES=controller,broker"
      - "KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093"
      - "KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      - "KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093"
      - "KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER"
      - "KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT"
    networks:
      - "debezium-net"

  kafka-ui:
    container_name: "kafka-ui"
    image: "provectuslabs/kafka-ui:v0.7.2"
    restart: "always"
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: "PLAINTEXT"
    depends_on:
      - "kafka"
    networks:
      - "debezium-net"

  debezium:
    container_name: "debezium"
    image: "quay.io/debezium/connect:2.7"
    restart: "always"
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "connect-configs"
      OFFSET_STORAGE_TOPIC: "connect-offsets"
      STATUS_STORAGE_TOPIC: "connect-status"
    depends_on:
      - "kafka"
    networks:
      - "debezium-net"

networks:
  debezium-net:
    driver: bridge
    name: debezium-net
